
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - deployment.ridecell.io
  resources:
  - mydeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deployment.ridecell.io
  resources:
  - mydeployments/finalizers
  verbs:
  - update
- apiGroups:
  - deployment.ridecell.io
  resources:
  - mydeployments/status
  verbs:
  - get
  - patch
  - update
